### ISSUE TITLE
SSL error thrown even with EnableUntrustedCertificates = true

### ISSUE THREAD

**Issue by vaindil** [alexrainman/ModernHttpClient#10]
I'm connecting to a local server that uses a self-signed SSL cert, so `EnableUntrustedCertificates` is set to `true`. I'm still getting the below error, however. Am I misunderstanding what `EnableUntrustedCertificates` is intended to do?

The exception:

```
Unhandled Exception:

System.Net.Http.HttpRequestException: Hostname my.hostname.local not verified:
    certificate: sha256/fake/hashstringhere=
    DN: CN=hostname.local
    subjectAltNames: [hostname.local, *.hostname.local, *.*.hostname.local] occurred
```

I'm declaring `HttpClient` like this:

```
_client = new HttpClient(new NativeMessageHandler
{
    AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate,
    EnableUntrustedCertificates = true,
    Timeout = TimeSpan.FromSeconds(6)
})
{
    BaseAddress = new Uri("https://my.hostname.local/")
};
```

**Comment by alexrainman** [comment]
Which platform?

**Comment by vaindil** [comment]
Sorry, this is on Android 7.1.1.

Package versions:

 * modernhttpclient-updated: 2.7.0
 * Xamarin.Forms 3.0.0.482510
 * all of Xamarin.Android: 27.0.2.

**Comment by alexrainman** [comment]
Cannot reproduce this. Can you provide a demo project?

**Comment by vaindil** [comment]
This is really odd, apparently it has to do with the certificate itself. When I test with `https://self-signed.badssl.com` the code works, but testing with `https://my.hostname.local` throws the error. I'll see if I can recreate the cert for a repro.

**Comment by vaindil** [comment]
[This is the exception that I get.](https://stackoverflow.com/questions/30745342/javax-net-ssl-sslpeerunverifiedexception-hostname-not-verified) I can't figure out why I get it. I can't repro either. Does that help at all?

**Comment by vaindil** [comment]
Today I learned that you can't have a two-level wildcard cert (like `*.*.example.com`). That was the issue. I fixed the cert and now all is good. Sorry about this!

**Comment by alexrainman** [comment]
No problem.
