### ISSUE TITLE
This is not an issue, but I don't know were to ask (Handshake failed)

### ISSUE THREAD

**Issue by OlegBabkin** [alexrainman/ModernHttpClient#11]
I'm trying to set your library, but requests do not work, all the time throws exception "Handshake failed" (I think that’s from OkHttp3). Tried to use on each platform separately and from base library, the same result. With adding NativeMessageHandler I'm using same parameters as in an example (Timeout = new TimeSpan(0, 0, 9), EnableUntrustedCertificates = true, DisableCaching = true). Server, that I working with has TLS 1.2 protocol.
Trying only with android, at the moment others platforms not realized yet.
I dont know where to search for a solution for that problem, please help me someone.

**Comment by alexrainman** [comment]
Take a look at this link and let me know if these is the same scenario you have: https://github.com/square/okhttp/issues/2669

**Comment by OlegBabkin** [comment]
Yes, I think the problem is same. Server, that I'm using is not allowing SSL usage. Is there any way to reconfigure getSslSocketFactory on OkHttp3 in your repo? (And yes, I'm using Android 7.0 for testing).

**Comment by alexrainman** [comment]
So, if your server is not allowing SSL, why you don't use HTTP. Just remove the S from it.

**Comment by OlegBabkin** [comment]
I dont have an access to the server configuration. Removing "S" from HTTP (in an endpoint) on my app do not resolves the problem (Same Handshake failure). I'll try to download your repo and change some OkHttp3 settings, maybe it will help. Also will try to use other platform.

**Comment by alexrainman** [comment]
That's actually what i do when EnableUntrustedCertificates = true, reconfigure getSslSocketFactory on OkHttp3. If you find a fix, please let me know.

**Comment by OlegBabkin** [comment]
Ok, anyway thank you for your help.

**Comment by alexrainman** [comment]
I am going to include a customTrustManager static property that can be initialized
