### ISSUE TITLE
[Android, iOS] Handling multiple Set-Cookie in the response

### ISSUE THREAD

**Issue by farcasclaudiu** [alexrainman/ModernHttpClient#13]
Multiple Set-Cookie in Http response are not handled in Android project.
Test project:
https://github.com/farcasclaudiu/TestModernHttpClient

it behaving the same even with the initial Paul McBets ModernHttpClient. :(

**Comment by farcasclaudiu** [comment]
Also. I have tested on iOS, the situation is the same :(

**Comment by alexrainman** [comment]
I will take a look.

**Comment by alexrainman** [comment]
Is it handled in other platforms?

**Comment by alexrainman** [comment]
Correcting this in next release.
