### ISSUE TITLE
What does EnableUntrustedCertificates do with the TSL connection?

### ISSUE THREAD

**Issue by nologinatgit** [alexrainman/ModernHttpClient#14]
When I use the client with `EnableUntrustedCertificates`, how does that effect the TSL connection? Is it still _encrypted_ with the certification of the server? Is it still a sort of valid SSL connection?

**Comment by alexrainman** [comment]
EnableUntrustedCertificates is intend for development environment, to give you the option to use your own self-signed certificate. Yes, still a valid encrypted SSL connection but, don't use on production environment.

**Comment by nologinatgit** [comment]
Thanks for the clarification, that was my opinion as well.
