### ISSUE TITLE
NotImplementedException when adding my client certificate

### ISSUE THREAD

**Issue by TGlev** [alexrainman/ModernHttpClient#17]
Hello,

When I try to do this:

```
var handler = new NativeMessageHandler(
                throwOnCaptiveNetwork: false,
                customSSLVerification: true
            );
            handler.ClientCertificates.Add(certificate);

            var httpClient = new HttpClient(handler);
```

I get a NotImplementedException thrown on the 
`handler.ClientCertificates.Add(certificate);`

Is there any other way to add my certificate? The server I'm trying to communicate with requires me to send this certificate.

**Comment by alexrainman** [comment]
I am going to release another version of the plugin that implementa two way certificate pinning.

**Comment by TGlev** [comment]
Too bad :(

Is there any way we can get around this?

**Comment by TGlev** [comment]
Is there a way with writing native code?

**Comment by alexrainman** [comment]
It is actually in native code but i have to change the plugin for that, which i already did but, i will release this week in a separated branch.

**Comment by TGlev** [comment]
That would be AWESOME!

**Comment by alexrainman** [comment]
Please, take a look at https://github.com/alexrainman/secure-modernhttpclient and let me know if that's what are you looking for.

**Comment by TGlev** [comment]
Yes, this is what Im looking for.
Please publish the code or a dll. :D

**Comment by alexrainman** [comment]
Early this week.

**Comment by TGlev** [comment]
Awesome, thank you.

**Comment by TGlev** [comment]
The nuget link doesnt work. :(

**Comment by alexrainman** [comment]
Wait, not released yet. Will do between today and tomorrow.

**Comment by TGlev** [comment]
Awesome, thank you. :)

**Comment by TGlev** [comment]
Is there a problem you need help with?

**Comment by alexrainman** [comment]
I just released the secure-modernhttpclient branch.
