### ISSUE TITLE
.netstandart 1.0 (PCL) support?

### ISSUE THREAD

**Issue by ignasbagdonas** [alexrainman/ModernHttpClient#18]
Hi, I want to use this, but we can't upgrade our app to netstandart 2.0 now.
Is there any solutions to use it with older Xamarin PCL project?

**Comment by alexrainman** [comment]
You can always install version 2.4.9.1 which supports PCL and can be installed on Net Standards 1.0

I tried to support it but some dependenciea don’t work.

**Comment by ignasbagdonas** [comment]
Thanks for quick response. Yes, it works. Thanks again.

**Comment by alexrainman** [comment]
It is not possible to support Net Standard 1.0 for compatibility issues.
