### ISSUE TITLE
Can not update package from v2.6.0 to v2.7.2

### ISSUE THREAD

**Issue by mohed** [alexrainman/ModernHttpClient#22]
Hi.

When attempting to upgrade the package from the nuget manager inside vs2017 i get the following error message. 

> Error: Could not install package 'modernhttpclient-updated 2.7.2'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I have the package installed in a portable library targeting .net v4.5, a xamarin.android project and a xamarin.ios projekt. What am I dowing wrong?

**Comment by InquisitorJax** [comment]
@mohed this nuget isn't meant to be used with .NET 4.5 libraries. If you want to create a shared library between android and iOS, you should be using .NET Standard libs - which this will support.
![image](https://user-images.githubusercontent.com/1822976/54830615-7d886280-4cc1-11e9-8c2b-6913459a5832.png)

**Comment by alexrainman** [comment]
I can fix that problem with a 2.7.3 release. In the meantime, add the reference to your shared pcl library manually. The dll will be at lib/netstandard20

**Comment by alexrainman** [comment]
I am releasing a new version that includes portable libraries support.
