### ISSUE TITLE
Can't install version 3.0.0 in iOS because BouncyCastle dependency

### ISSUE THREAD

**Issue by rayita** [alexrainman/ModernHttpClient#26]
I'm unable to install version 3.0.0  in iOS because BouncyCastle dependency.
There is no Xamarin iOS compatible BouncyCastle nuget package.

**Comment by alexrainman** [comment]
Why I can? I developed the plugin using this nuget https://www.nuget.org/packages/BouncyCastle/ and it can be installed in any iOS project.

**Comment by rayita** [comment]
I don't know why you can and I can't, but when I try to install  BouncyCastle nuget package (same as you) I get this error message:

NU1202: Package BouncyCastle 1.8.5 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package BouncyCastle 1.8.5 supports: net (.NETFramework,Version=v0.0)

**Comment by leo-mck** [comment]
I am also having this problem. And if I try to directly install "BouncyCastle 1.8.5" on a new XF app, I get:
```
NU1202: Package BouncyCastle 1.8.5 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0). Package BouncyCastle 1.8.5 supports: net (.NETFramework,Version=v0.0)
NU1202: Package BouncyCastle 1.8.5 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win. Package BouncyCastle 1.8.5 supports: net (.NETFramework,Version=v0.0)
NU1202: Package BouncyCastle 1.8.5 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x64. Package BouncyCastle 1.8.5 supports: net (.NETFramework,Version=v0.0)
NU1202: Package BouncyCastle 1.8.5 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package BouncyCastle 1.8.5 supports: net (.NETFramework,Version=v0.0)
```

I can, however, install the package "Portable.BouncyCastle 1.8.5" normally.

**Comment by alexrainman** [comment]
Can you guys try version 1.8.4?

**Comment by rayita** [comment]
Same result

**Comment by alexrainman** [comment]
@rayita can you confirm you can install Portable.BouncyCastle 1.8.5?

**Comment by rayita** [comment]
Yes, I can.
The main difference between both package is that BouncyCastle does not declare wich frameworks are compatible with in nuspec file, and Portable.BouncyCastle does.

**Comment by alexrainman** [comment]
Weird. Still wonder why I can install it. Going to release a package update just to change this dependency in iOS.
