### ISSUE TITLE
iOS Timeout use wrong TimeSpan value

### ISSUE THREAD

**Issue by NazarHuliiev** [alexrainman/ModernHttpClient#31]
Hi @alexrainman . iOS handler use wrong value for timeout. Because of that  there is no way to set more than 59 seconds. You should use TotalSeconds instead of Seconds in this line. https://github.com/alexrainman/ModernHttpClient/blob/f1de9a2f281b49a6c91e74ebc74914c1db657c1f/ModernHttpClient.iOS/NSUrlSessionHandler.cs#L217

Can you fix it and release new version?
Thank you.

**Comment by alexrainman** [comment]
Yes I can do that.

**Comment by NazarHuliiev** [comment]
I created pull request for this. Thank you.

**Comment by alexrainman** [comment]
It is already fixed on my side.

**Comment by NazarHuliiev** [comment]
Thank you very much.
