### ISSUE TITLE
Pin wildcard hostnames

### ISSUE THREAD

**Issue by xabre** [alexrainman/ModernHttpClient#34]
First of all thank you for breathing life back into the ModernHttpClient. 
I have a question regarding defining hostnames for pins. 

The current implementation seems to only accept complete hostnames like: `test-example.com`

We have several subdomains/enviornments for our app and I would like to pin them all using a single `Pin` entry. For example: `dev.test-example.com`, `prod1.test-example.com`, `prod2.test-example.com`. 

The app should be able to deal with new sub-domains without us having to add a new certificate pin and rebuild. It would be totally cool to be able to pin something like `*.test-example.com`.

Is this possible with your current implementation or is it planned as a future enhancement?

**Comment by alexrainman** [comment]
Is this the same as #33? That I will do but, your sub-domains need to be included in the certificate. What is failing here is not the pins themselves but the hostname validation.

**Comment by xabre** [comment]
I wouldn't dismiss it that easy. The underlying OkHttp implementation for Android already supports this: https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html -> see wildcard pinning section.

**Comment by alexrainman** [comment]
Will definitely take a look.

**Comment by alexrainman** [comment]
HA, I can easily do it. Expect a new version later today.

**Comment by alexrainman** [comment]
It will be out today.

**Comment by xabre** [comment]
Thanks for the quick implementation. I have tested this out today and it works as expected on Android but there is an issue on UWP.

I have narrowed it down to the following section of `ModernHttpClient/ModernHttpClient/Utility.cs`

`
#if __PORTABLE__ || WINDOWS_UWP
            if (string.Compare(hostname, end) != 0) {
                return false;
            }
#else
            if (string.Compare(hostname, length, end, 0, end.Length, true, CultureInfo.InvariantCulture) != 0)
            {
                return false;
            }
#endif
`

specifically the `#if __PORTABLE__ || WINDOWS_UWP` does not account for the sub-string of hostname and thus always compares the full hostname with the sub-pattern. The fix would be to compute the substring of the hostaname starting from the first '.' and then compare.

Example:
hostname = test.example.com
pattern = *.example.com

for UWP will compare `test.example.com` with `.example.com` and will always fail :(

**Comment by alexrainman** [comment]
Ok will fix that later today.
