### ISSUE TITLE
Allow http communication

### ISSUE THREAD

**Issue by jded76** [alexrainman/ModernHttpClient#35]
Is there any chance that you will allow http communication again in the new version?
I'm using this library for internal communication (not internet) and I'm not using https.

I know this is not the right way, but the overhead of installing (and renewing) certificates is not an option in our situation (due to lack of IT Department).

Anyway thank you for your time and effort.

**Comment by alexrainman** [comment]
There will be a new flag in the next release to disable TLS. That will allow HTTP communication.

**Comment by jded76** [comment]
Thank you again, but unfortunately, I'm only using Android. 

I already saw that the OKHttp supports that, with the CLEARTEXT ConnectionSpec, but I couldn't do it without a code change from you.

That's why I asked you if you are planning to do anything about it.

**Comment by alexrainman** [comment]
Version 3.3.0 is out.

**Comment by jded76** [comment]
Thank you very much!

I'll have a look as soon as I get home.

**Comment by alexrainman** [comment]
Releasing 3.3.1 to follow your advice.

**Comment by jded76** [comment]
Good job! It's working with http again.
Thank you very much!
