### ISSUE TITLE
Proxy authentication ignored on Android

### ISSUE THREAD

**Issue by xabre** [alexrainman/ModernHttpClient#36]
Unfortunatly IWebProxy.Credentails are not passed to the `OkHttp.Builder.proxyAuthenticator` and thus ignored.

The following stackoverflow post describes how to set a proxy authenticator for OkHttp: https://stackoverflow.com/questions/35554380/okhttpclient-proxy-authentication-how-to

**Comment by alexrainman** [comment]
Bene trying to find a reference for the right keys to use in iOS to pass credentials to NSUrlSessionDelegate proxy configuration. No luck.

**Comment by xabre** [comment]
Based on my experience with proxy authentication and iOS manually setting the proxy credentials for NSUrlSession is not a normal use case. iOS has OS level support for proxy authentication (wlan settings) and by using NSUrlSession this is implicitly used by the app. This feature successfully solved my "enterprise" use case without having to manually mange proxy credentials (like on android).

**Comment by alexrainman** [comment]
I get your point but, I have to provide same functionality in all platforms.

**Comment by alexrainman** [comment]
Looking on how it is done on Android, where ```Proxy-Authorization``` is added as request header, reproducing the same behavior in iOS adding the credentials as part of the NSUrlSession configuration HttpAdditionalHeaders.
