### ISSUE TITLE
Is It necessary yet ?

### ISSUE THREAD

**Issue by candidodmv** [alexrainman/ModernHttpClient#39]
The functionality of ModernHttpClient (i.e Native SSL/Tls) is now built into Xamarin and can now be configured at the platform level as per below links:

iOS - https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/http-stack
Android - https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/http-stack?tabs=windows

is this project fulfill something further?

**Comment by alexrainman** [comment]
@candidodmv yes it does.

Xamarin HttpClient stack doesn't support:

- Native Cookie handler
- Timeout
- Disabling caching
- Web Proxy
- And the more important one: Mutual TLS Authentication (MTLS).

This library also supports cleartext http and self-signed certificates which can be very useful in testing environments. Both properties help to identify if developers are shipping insecure applications while automating build pipelines.

I talked to @jamesmontemagno during the #XamarinDevSummit about merging what this branch offers into the original one. It can also means bringing it to the Xamarin Stack.

**Comment by alexrainman** [comment]
@candidodmv 230K+ downloads in Nuget, and counting.
That is saying something no?

**Comment by candidodmv** [comment]
That's great! Now after your details it's possible to figure out where this project aims to accomplish.

There's a misconception between those solutions mainly because of they are has the same name, what follows up to understand that is the same thing.

But, will be really  very important this project to atached iwth Xamarin Stack to avoid any other confusion. 

moreover, another reason there's a lot of article linking to the previous version of this library [https://github.com/anaisbetts/ModernHttpClient](https://github.com/anaisbetts/ModernHttpClient), by the way It seems was discontinued.

**Comment by alexrainman** [comment]
By this project name you can figure it out that it is a branch from the original one created by Paul Betts, which he hasn’t been able to update in a few years. That’s why i took over and created it.
