### ISSUE TITLE
Can I just pin the public key, not the cert?

### ISSUE THREAD

**Issue by ppastor** [alexrainman/ModernHttpClient#40]
Hi Alex,

We are currently using the older (original) branch of the ModernHttpClient. Since certificates expire every few years we are just pinning the cert's public key. This works well enough, but we noticed some strange behavior using 3G... WIFI works fine. I thought since you have a supported branch of this project that we would try to upgrade. My team is telling me that it appears cert pinning is a requirement (IOW, we can't just use the key pinning). Is this correct?

Thank you.

**Comment by alexrainman** [comment]
@ppastor there are bunch of validations that are done before the public keys validation.

Check all the code before this line: https://github.com/alexrainman/ModernHttpClient/blob/738bfd9b7769e00484d83a3d7e935459482fe298/ModernHttpClient.Android/OkHttpNetworkHandler.cs#L483

I have been thinking on changing that on the next release, in a way that you can set the type of server certificate validation you want to do:

- Certificate
- Public Keys
- Both

**Comment by alexrainman** [comment]
This will be out in next release.
