### ISSUE TITLE
'NativeMessageHandler' does not contain a definition for 'EnableUntrustedCertificates'

### ISSUE THREAD

**Issue by stesvis** [alexrainman/ModernHttpClient#45]
Hello,

the EnableUntrustedCertificates property seems to have disappeared in  version 3.3.4.

My code used to be like this:
`var client = new HttpClient(new NativeMessageHandler() { Timeout = new TimeSpan(0, 0, 30), EnableUntrustedCertificates = true, DisableCaching = true });`

but now i get the exception:

> 'NativeMessageHandler' does not contain a definition for 'EnableUntrustedCertificates'

What should I do from now on? thx

**Comment by alexrainman** [comment]
@stesvis TLSConfig has a property named DangerousAcceptAnyServerCertificateValidator. Use that.

**Comment by stesvis** [comment]
My bad, i should have searched it in the release notes, thank you.
