### ISSUE TITLE
Calling HttpClient methods should throw .Net Exception when fail

### ISSUE THREAD

**Issue by Gimly** [alexrainman/ModernHttpClient#5]
If there is an error with one of the HttpClient method, for example if the connection is lost, `ModernHttpClient` will bubble up the exception coming from the underlying API.

For example, on Android, it will bubble up the exception `Java.Net.UnknownHostException` if he cannot find the host.

This makes it very difficult to catch exceptions from .Net, for example if we're using the library in a Xamarin Forms project. It also means that HttpClient doesn't behave exactly like the "real" `HttpClient`.

Instead of bubbling up the library's exception, it should catch those exception and throw an `HttpRequestException`, like the real `HttpClient`.

**Comment by alexrainman** [comment]
Let me see how i can implement that. It makes sense.

**Comment by alexrainman** [comment]
Done. Wait for updated version.

**Comment by Gimly** [comment]
Awesome, that was quick 😄!

Did you do the same thing for iOS?

**Comment by alexrainman** [comment]
iOS already do it.

**Comment by Gimly** [comment]
Hi, I just checked, the change and I saw that you sent a root `Exception`, but that's not really better than the previous option with bubbling the java exception. It would be much better if you were throwing a HttpRequestException.

Ideally, you should also put the Java exception you got in the InnerException.

**Comment by alexrainman** [comment]
Ok. Will do that when i get back. Will be out for a few days off the grid :)
