### ISSUE TITLE
Can ModernHttpClient send X509 certificates to safariviewcontroller a webview, and the Android equivalent?

### ISSUE THREAD

**Issue by AA-65537** [alexrainman/ModernHttpClient#50]
I need to use a custom X509 certificate store when accessing a website, where I have different trusted roots, and also have a client certificate.

Can I use ModernHTTPClient to make and secure the connection, and then leverage a browser to display the HTML contents?

**Comment by alexrainman** [comment]
I think it is possible in Android overriding the WebView client and using modern to load the content:

webView.setWebViewClient(new WebViewClient() {
    @Override
    public boolean shouldOverrideUrlLoading(WebView view, String url) {
        // Insert your code here
    }
});

**Comment by alexrainman** [comment]
UIWebView delegate has similar method:

-(BOOL)webView:(UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request navigationType:(UIWebViewNavigationType)navigationType
