### ISSUE TITLE
Not sure quite how to build the project

### ISSUE THREAD

**Issue by codingJWilliams** [alexrainman/ModernHttpClient#53]
Hello,

Forgive me, C# novice trying to add functionality to another application, however was hitting into issue #41 
I have cloned the project in Visual Studio 2019, modified the [OkHttpNetworkHandler.cs](https://github.com/alexrainman/ModernHttpClient/blob/master/ModernHttpClient.Android/OkHttpNetworkHandler.cs) file, and built the changes, however I'm not quite sure how to include it in another Visual Studio Xamarin project (specifically https://github.com/bitwarden/mobile) - usually I would add packages through `Manage NuGet Packages` however I cannot do that here due to the fact that my modified version is not on NuGet.
Once I've verified my changes resolve the issue with subject alternative names not being matched, I will PR them here :)

Thanks, Jay

**Comment by alexrainman** [comment]
Just reference the modernhttpclient project on each of your platform specific projects.
