### ISSUE TITLE
Android Network related exceptions on latest devices

### ISSUE THREAD

**Issue by cybvitthal** [alexrainman/ModernHttpClient#54]
Many times, We are facing 3 network related issues mostly in Android 9(Samsung galaxy).

1. `NativeMessageHandler+<SendAsync>d__22.MoveNext (), “Socket closed” exception.`
2. `android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)`
3. `isConnected failed: ECONNABORTED (Software caused connection abort)`

It was working previously till Android 8.

Can you help on this?

**Comment by cybDevendra** [comment]
@alexrainman,
what will be the quick fix or any workaround for this issue?
Thanks in Advance :)

**Comment by alexrainman** [comment]
I will need to run some tests on Android 9.

**Comment by Kingamattack** [comment]
I mostly have the **NativeMessageHandler+<SendAsync>d__22.MoveNext (), “Socket closed” exception**. And yes it's very difficult to track as it's totally random...

As @cybDevendra said, it happens mostly on Android 9

**Comment by alexrainman** [comment]
Including support for Http2 in the next release. That may fix this issue.

**Comment by alexrainman** [comment]
Is this issue resolved?
