### ISSUE TITLE
custom validation of self-signed cert

### ISSUE THREAD

**Issue by tele-bird** [alexrainman/ModernHttpClient#55]
For connecting to our IoT device's SSL endpoint, we need to use a self-signed certificate, and we want to validate its MD5 and SHA1 hash strings like this:

```
    public static class HttpsValidation
    {
        public static void Initialize()
        {
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            ServicePointManager.ServerCertificateValidationCallback = OnValidateCertificate;
        }

        static bool OnValidateCertificate(object sender, X509Certificate certificate, X509Chain chain, SslPolicyErrors sslPolicyErrors)
        {
            string md5Hash = certificate.GetCertHashString(System.Security.Cryptography.HashAlgorithmName.MD5);
            string sha1Hash = certificate.GetCertHashString(System.Security.Cryptography.HashAlgorithmName.SHA1);
            return md5Hash == "myMD5hash" && sha1Hash == "mySHA1hash";
        }
    {

```
However, with modernhttpclient-updated, I only see ways to validate the public keys, and I can't customize the validation.  Is it not possible?

**Comment by alexrainman** [comment]
I just released a new version yesterday but this is not supported yet. I will have to take a look into it.

**Comment by alexrainman** [comment]
Done in version 3.4.1

**Comment by tele-bird** [comment]
Great, thank you!  How do I set up custom validation?  I don't see any mention of it in README.md

**Comment by alexrainman** [comment]
You don’t. Just pass the public keys in the format of your preference and it will work.

**Comment by tele-bird** [comment]
Ok, so we want to validate **both** MD5 **and** SHA1, as in the code snippet I provided.  Is there a way to pass both formats, and have it check that MD5 equals cert1 **and** SHA1 equals cert2 ?

**Comment by alexrainman** [comment]
Pass both them for the associated domain with the certificate.

**Comment by tele-bird** [comment]
When I pass in a **valid** sha1 or md5 base64 string, I get the FormatException (The input is not a valid Base-64 string.) . After analyzing the problem, I found a bug in Utility.cs:

Currently, line 85 in VerifyPins() method assumes the prefix is 7 characters in length:

`
                    byte[] bytes = Convert.FromBase64String(pin.Remove(0, 7));
`
This is completely legit for "sha256/", but not "sha1/" or "md5/".

To fix this bug, you could change it like this:

`
                    byte[] bytes = Convert.FromBase64String(pin.Remove(0, pin.IndexOf('/') + 1));
`
