### ISSUE TITLE
Timeout can't exceed 60s

### ISSUE THREAD

**Issue by chris-tradify** [alexrainman/ModernHttpClient#60]
Due to some awkward requirements, it is necessary to have a timeout of more than a minute in some rare cases, however even when setting the NativeMessageHandler timeout to 5mins, the connection times out after 1 minute. 

I am using SendAsync to send an HTTP Post request. Is there a way to make the httpclient respect the longer timeout?

**Comment by alexrainman** [comment]
The answer is no. A timeout longer than a minute is not supported by the platform specific libraries.
