### ISSUE TITLE
Fiddler Support

### ISSUE THREAD

**Issue by simader** [alexrainman/ModernHttpClient#70]
Is it possible to configure the NativeMessageHandler in UWP that you can trace the traffic in Fiddler?
At least in DEBUG.

I get a HttpRequestException when i use the NativeMessageHandler. But it is possible when I use the standard HttpClientHandler.

Best,
Andreas

**Comment by alexrainman** [comment]
Yes, you can provide a WebProxy as last parameter https://github.com/alexrainman/ModernHttpClient#how-to-use-a-web-proxy
