### ISSUE TITLE
NullReferenceException in OKTaskCallback.OnFailure

### ISSUE THREAD

**Issue by chris-tradify** [alexrainman/ModernHttpClient#75]
I don't have any reproduction steps, however I have a seen a high number of crashes happening in the OKTaskCallback.OnFailure method due to an NRE. My stack trace doesn't give much more detail than that, but I wonder if the changes proposed in https://github.com/alexrainman/ModernHttpClient/pull/65 would fix it, as it does seem possible that the IOException could have a null message?

**Comment by alexrainman** [comment]
There's an active PR i will be merging soon that solves this issue.

**Comment by alexrainman** [comment]
Merging this in the next release.
