### ISSUE TITLE
MissingMethodException Method 'ModernHttpClient.NativeMessageHandler..ctor' not found.

### ISSUE THREAD

**Issue by kpespisa** [alexrainman/ModernHttpClient#9]
I had to remove the minimumSSLProtocol parameter on the NativeMessageHandler constructor in NSUrlSessionHandler.cs to get this working on iOS. I assume it is due to the signature being different than the library's constructor? 

However, I only did this in iOS and did not need to change anything on my Android project.

**Comment by kpespisa** [comment]
I created a small example. I'm using Xamarin.IOS and Visual Studio for Mac, in case that is part of the issue. 
[MHCTest.zip](https://github.com/alexrainman/ModernHttpClient/files/1974235/MHCTest.zip)

**Comment by michaelgobbers** [comment]
I'm having the same issue.

**Comment by alexrainman** [comment]
Fixing it.

**Comment by alexrainman** [comment]
I think this is related to the fact that my netstandard support is not working as expected. I am migrating the plugin to a multi-target project.

**Comment by alexrainman** [comment]
Version 2.7.0 has been released. Please test.

**Comment by kpespisa** [comment]
This issue still exists in 2.7.0. You can reproduce the issue if you download the example project (MHCTest.zip) and update the nuget package in the projects.

**Comment by alexrainman** [comment]
Somehow the plugin is not working as expected in .netstandard with the original architecture from Paul. Going to migrate it to default Xamarin plugin Lazy load style.

**Comment by alexrainman** [comment]
Fixed
